apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: anonymous-bird-python 
  janus-idp.io/tekton: anonymous-bird-python
  backstage.io/kubernetes-id: anonymous-bird-python
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: anonymous-bird-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  