apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: anonymous-bird-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: anonymous-bird-python 
  name: anonymous-bird-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: anonymous-bird-python 
